CREATE TABLE TUTOR (
    id_tutor INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    endereco VARCHAR(150),
    telefone VARCHAR(15),
    email VARCHAR(100)
   ).
CREATE TABLE paciente (
    id_paciente INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    especie VARCHAR(50) NOT NULL,
    raca VARCHAR(50),
    idade integer,
    peso numeric(15,2),
    id_tutor INTEGER,
    FOREIGN KEY (id_tutor) REFERENCES tutor (id_tutor)
)

CREATE TABLE veterinario (
    id_veterinario INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    especialidade VARCHAR(100),
    telefone VARCHAR(15),
    email VARCHAR(100)
)

CREATE TABLE agendamento (
id_agendamento INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
data_hora timestamp NOT NULL,
motivo VARCHAR(255),
id_paciente integer NOT NULL,
id_veterinario INTEGER NOT NULL,
FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente),
FOREIGN KEY (id_veterinario) REFERENCES veterinario (id_veterinario)
)

CREATE TABLE medicamento (
id_medicamento INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY, 
nome VARCHAR(100) NOT NULL,
descricao VARCHAR(255),
preco numeric(10,2)
)

CREATE TABLE RECEITA (
    id_receita INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    data_emissao DATE NOT NULL,
    id_agendamento INTEGER NOT NULL,
    FOREIGN KEY (id_agendamento) REFERENCES agendamento (id_agendamento)
)

CREATE TABLE ITEM_RECEITA (
    id_item_receita INTEGER GENERATED BY default AS IDENTITY PRIMARY KEY,
    quantidade INTEGER NOT NULL,
    dosagem VARCHAR(50),
    id_receita INTEGER NOT NULL,
    id_medicamento INTEGER NOT NULL,
    FOREIGN KEY (id_medicamento) REFERENCES medicamento (id_medicamento)
)
